export const ActionTypes = {
  //Pets
  SET_PET: "SET_PET",
  SELECTED_PET: "SELECTED_PET",
  ADD_SELECTED_PET: "ADD_SELECTED_PET",
  EDIT_SELECTED_PET: "EDIT_SELECTED_PET",
  REMOVE_SELECTED_PET: "REMOVE_SELECTED_PET",

  //Tasks
  SET_TASK: "SET_TASK",
  SELECTED_TASK: "SELECTED_TASK",
  ADD_SELECTED_TASK: "ADD_SELECTED_TASK",
  EDIT_SELECTED_TASK: "EDIT_SELECTED_TASK",
  REMOVE_SELECTED_TASK: "REMOVE_SELECTED_TASK",

  //Payments
  SET_PAYMENT: "SET_PAYMENT",
  SELECTED_PAYMENT: "SELECTED_PAYMENT",
  ADD_SELECTED_PAYMENT: "ADD_SELECTED_PAYMENT",
  EDIT_SELECTED_PAYMENT: "EDIT_SELECTED_PAYMENT",
  REMOVE_SELECTED_PAYMENT: "REMOVE_SELECTED_PAYMENT",
  UPDATE_CHART: "UPDATE_CHART",
};
